---
title: "GIS homework 4"
author: "DB"
date: "29/10/2021"
output:
  pdf_document: 
    latex_engine: xelatex
  word_document: default
  html_document:
    df_print: paged
---


# Inequality task- Week 4
Task: 
Join the global gender inequality index to spatial data of the World, creating a new column of difference in inequality between 2010 and 2019

## Reproduce

```{r renv, eval=FALSE}

# take a snapshot with
#renv::snapshot()
#install the same packages
#renv::restore()

```

# Load packages

```{r packages}
library(tidyverse)
library(sf)
library(janitor)
library(here)
library(countrycode)
# install.packages("countrycode")


```
## Read in data:

Located within the Data folder:

* GII (Gender Inequality Index) from: http://hdr.undp.org/en/indicators/68606#
* Wold Shapefile from: https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-2.688200%2C0.000000%2C1.41

```{r read in data}

GII <- read_csv(here::here("Gender Inequality Index (GII).csv"),
                locale = locale(encoding = "latin1"),
                na="..",
                skip=5)

Worldmap <- st_read(here::here("World_Countries_(Generalized)","World_Countries__Generalized_.shp"))

```

## column names

```{r columns}

GIIcols <- GII %>%
  clean_names %>%
  select(country,x2019,x2010)%>%
  mutate(difference=x2019-x2010) %>%
  slice(1:189,)%>%
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))

```

## join the data

```{r join}
JoinGII <- Worldmap %>%
  clean_names() %>%
  left_join(.,GIIcols,
            by = c("aff_iso"="iso_code"))
```

## make a preliminary map

```{r preliminary plotting}
library(tmap)
library(tmaptools)

tmap_mode("plot")
qtm(JoinGII,
    fill = "difference")
```
## pick some colours

```{r colours}
library(RColorBrewer)
library(shiny)
library(shinyjs)
tmaptools::palette_explorer()
```

## nicer map

```{r final map}

breaks = c(-0.2, -0.175, -0.15, -0.125, -0.1, -0.075, -0.05, -0.025, 0 )
tm1<-tm_shape(JoinGII)+
  tm_polygons("difference",
              breaks=breaks,
              palette="RdYlGn")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("Difference in Gender Inequality Index between 2019 and 2010", position=c(0.2,0), size=0.75)

legend <- tm_shape(JoinGII) +
    tm_polygons("difference",
                palette="RdYlGn") +
    tm_scale_bar(position=c(0.2,0.1), text.size=0.6)+
    tm_compass(north=0, position=c(0.55,0.1))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) arcgis and undp", position=c(0.2,0.0))
  
t=tmap_arrange(tm1,legend, ncol=1)

t
```

